image: pomma89/dotnet-mono:dotnet-2-mono-5-sdk
stages:
- test
- deploy

test:
  stage: test
  script:
  - dotnet cake build.cake -Target=Test

pages:
  stage: deploy
  script:
  - dotnet cake build.cake -Target=Docs
  - mkdir public
  - mv docs/* public
  artifacts:
    paths:
    - public
  only:
  - master

push:
  stage: deploy
  script:
  - dotnet cake build.cake -Target=Push
  only:
  - tags